### ISSUE TITLE
Most cited / Most Viewed CSV download limit

### ISSUE THREAD

**Issue by bakerac4** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#50]
I am currently implementing the most cited and most viewed csv downloads. I realized that even though I send in no `limit` you seem to still be applying one. 

So if I just load the page and hit the download button there should be 5426 results, however I only get returned 10 of them in the CSV.

https://stage-api.pep-web.rocks/v2/Database/MostViewed/?period=all - returns a full count of 45
https://stage-api.pep-web.rocks/v2/Database/MostViewed/?period=all&download=true returns 5 items

**Comment by nrshapiro** [comment]
@bakerac4 

There isn't a way currently to say no limit.  0 means 0.  No entry is the default as shown in the DOCS page.  You could set it to 100,000 or so and that should cover you :)  

I wanted to default it to a fixed number, because with no limit, for a call to return JSON, it can be a lot of records, and slow.  But I'll change it in a future build so some value means no limit.  Maybe 0, maybe -1?  Probably 0 since that would be pretty meaningless if you asked for 0 records back.  I still wouldn't want someone to try to pull all the records back at once in JSON.

**Comment by nrshapiro** [comment]
@bakerac4 

Coded for the next release:

- if you don't change the default limit from it's setting, but you select download, you will get all the records.
- To limit the download, just pick a number for limit other than the default.
- Otherwise, I've left the limit in place for documentListItem returns.

Ok?

**Comment by bakerac4** [comment]
@nrshapiro I think all of the above makes sense. Thanks for the help!

**Comment by bakerac4** [comment]
@nrshapiro Im still not seeing all results.

https://stage-api.pep-web.rocks/v2/Database/MostCited/?period=all&queryType=MostCited&offset=0&download=true

Did this end up getting released?

**Comment by nrshapiro** [comment]
@bakerac4 

Working on it today...I've had to wait until I had cited and views data again after dumping my solr database to write the new load programs.  Next release.

**Comment by nrshapiro** [comment]
@bakerac4 

A new build ver 2020.0916.1.Alpha uploaded this morning...it doesn't limit returns and it appears the solrpy library can't handle the full set so unless you restrict it using the filters, it will error out.

I've change the pending development build to set the maximum number of records now that the server can return at once in OpasConfig, and for now I'm setting it to 500 to be safe (I was playing with some of the limits online, and they're lower than if I run here locally).  While I could walk through the Solr set 500 or so at a time, bringing back as many as 136000 records is going to be a nightmare for the user, since the server will keep going at it for 5-10 minutes and they'll be no stopping it.  And looking at the Views download on PEP-Web, it's over 90,000 records.

I think the best solution here, is for you do do the download incrementally using the limit and offset, perhaps up to 500 at a time, probably want to do less though...while giving the user the feedback of a downloading box with a progress bar and a cancel button.  That's how it works on PEP-Web.  You will know how many records there are to start, because it will be in the last visual display you did.  You could even warn the user that this will take "some time" :)

Before you do that though, I'm going to look at getting the data from RDS instead.  There are some issues with that though, in terms of the search/filtering being different than it would be with what they're looking at in Solr.

I'll let you know if that looks like it will work out and be able to grab the set in a timely fashion, even for 136,000 records.  Otherwise, I think we'll need to go with plan B, above, since that has the advantage of giving feedback and control to the user during the wait.

**Comment by nrshapiro** [comment]
@bakerac4 

I think I've got this resolved...at least it's a lot faster, and can return much larger sets, virtually unlimited via a streamed approach to the results.  Of course, I don't have a large enough set to test yet, but I've done it to 40K records.

The down side, though slight, is that, to get sufficient performance, I'm using the RDS database for the data, which means that the filtering may not be exactly the same set as Solr produces for the browser display...and if the data in Solr are slightly out of date due to the update process not being run for a day or two, the data will be slightly different. But it's a fair tradeoff.  Grabbing the data from Solr was unworkable for the uber large set because of the time it takes.  RDS is much faster here.  

If this is a problem, we could do the stat tables in the browser from RDS, but the complication is that with RDS, you don't have the opportunity to get the other DocumentList data delivered to the app.  That's especially a problem for the infoCard rather than the table, but I see issues for both.  So I think the dual approach is best for now, and the slight potential difference in the data is a reasonable compromise.  

It will be easier to see the impact once it's online and the client is using it.

Next push, but I have multiple things going on, so probably a few more days.

**Comment by nrshapiro** [comment]
@bakerac4 @billdami @adistasio 
I tested this on the latest gavant client and it works.  However, while it looks complete, the record count is far below the number shown when you go to the table for citations or views.  But that number appears to be wrong.  In fact, the download contains more records than the table will show me, and that's still far below the number at the top of the screen.  

For Views, the client showed me 130,114 results in the label at the top, almost all the articles in the database.  It's not likely to be right.  The online table for most views though stops scrolling down after about 200 records.  The download file contains 3276 records (including header) and this matches the RDS database view it comes from, so it's correct.  

For Citations, the client shows 43,607 results in the label at the top, which does sound about right in terms of running the input filter.  But the mostcited crosstab with details view in the RDS database, where the download comes from has 43366 records.  The mostcited crosstab itself has 44353 records...I'm not sure why some records are lost in the detail join yet, but I'll have to look into that.  The download however falls short of both of these: I only received 15130 records.  Again, I'll have to investigate why.  (I had hoped to close this based on the downloads appearing to be working fine, but given this disparity, leaving it open.)
