### ISSUE TITLE
Related Documents

### ISSUE THREAD

**Issue by billdami** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#53]
> [Core]​ ​Related Documents​ - This card shall show the related documents to the current document, as implemented in PEP-Web, where instead there's an icon to indicate there are related documents for this document next to the title.
a. Note that not all documents have related documents, however. Those that do, have the
document id for the "main" document set in the artqual element of the XML; this comes back in
the documentListItem as ​relatedrx.​ This value is also available for search using the a termList
to specify since art_qual is not a search parameter. Example termlist in search endpoint (in
body):
{ ​"artLevel"​: ​1​,
"query"​ : {
"words"​: ​"AJP.016.0003A" }
"field"​ : ​"art_qual"​,
[
] }

@nrshapiro Is there any technical limitations blocking you from exposing the `art_qual` field as a normal GET param on the /Search/ endpoint? And if not, would it be possible for you to add this, as another way for us to fetch related documents for a given document ID?

This would be preferable for us, as our frontend framework/data layer does not normally support POST/body requests for "get resource" type requests (it is reserved for "create resource" requests), so we are trying to avoid having to use POSTs and request bodies for search requests if at all possible (though we can work on implementing this if its absolutely necessary).

cc @bakerac4

**Comment by nrshapiro** [comment]
@billdami The only reason is that I feel there are already too many GET parameters to the search (makes it harder to use the OpenAPI docs interface to explore).  Why not just use parameter fulltext1?  That works now:

art_qual:(IJP.076.0315A)

I do think there is a semantic advantage however to adding it to the query parameters, since it makes it more schema independent from the client point of view.  For now, use the above workaround and I'll add this to possible future enhancements.  Adding a new query parameter is a bit more involved in the API because of the normalization layers I have to allow parameter processing by different calls to share code.

I agree POST is unclear for get type requests, but unfortunately, some forces on the internet seem to be trying to prevent GET requests from including a body (including Google apparently), and the OpenAPI docs interface no longer supports GET requests with a body, hence I've added all the POSTS.  But it's good to know you can't use them...I was thinking about deprecating the GET versions later since the POST does everything GET does, and the API is getting too big (at least from a comprehension point of view).  We'll have to see about direction later.

**Comment by billdami** [comment]
@nrshapiro yeah I agree on having too many GET parameters (also I think there is an upper limit for a URL's query param string length, a limitation request bodies do not have). I didn't realize this could be done with just another fielded fulltext1 value, so that should work fine for our purposes.

POST for get type requests is definitely possible for us, its just not what the framework supports out of the box, so we can definitely discuss refactoring to this path later on, just knowing it'll take some additional work on our end.
