### ISSUE TITLE
Glossary definition endpoint

### ISSUE THREAD

**Issue by bakerac4** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#57]
@nrshapiro 

Im working on the Glossary Terms sidebar widget

```
a. Hovering over a term in the cloud shall show a hoverbox with its definition as a PEP Glossary
Popup
```

I have gotten the glossary_group_terms from the search and Im now displaying the word cloud. On hover Im trying to figure out how to load the definition using just the term I have i.e. "material" but there doesn't seem to be an endpoint for that? 

The other thing I wanted to mention is what we are trying to display in a tooltip is quite large, and hover and mobile doesn't play nice together either. Would you guys be open to considering the following?

Click on the word and it will open a modal. At the bottom of the modal in the footer there can be a search by this term link which would then preform the search?

**Comment by nrshapiro** [comment]
I've modified /Documents/Glossary to accept the term-name or term-group-name.  Note that you will get more than one DocumentListItem when asking for a group (which is what PEP-Easy does, see below).

 _This is implemented in the 2020-09-12 build on stage._

I also realized that that endpoint had not been updated for the PaDS document authorization process...so I did that too.  

And added a "partial return" feature for non-authenticated users.  We previously did not allow anyone to click on glossary words in a document when you weren't logged in.  The link wasn't active in that case.  Now you can allow it because the endpoint will return the first paragraph of Glossary entries and a message about subscribing if the user isn't authorized or logged in.  I figured that was necessary for the glossary word cloud.

I am fine with clicking on the term in the word cloud and getting the same modal you get if you click on a term in the document itself.  Here's an example of what that modal looks like in PEP-Easy.  It can get pretty long for some entries (even though that feature hides some of the text under a click-to-open excerpt -- this excerpt is different than the I'm talking about above for non-authorized users--the glossary entries, which are often too long for this, have a tagged excerpt section you can hide and open on click)

Something we can discuss, if you prefer: Alternatively, you could present the glossary item  in the main (center) window, instead of a popup, as long as the back button in the browser, and potentially a special "Back to the document" button on that window takes them back to whatever was in the main (center) window before.  That may not look as good for smaller entries...there are some, but might be better for bigger groups.

![image](https://user-images.githubusercontent.com/4837554/93019589-fa8a5480-f5a5-11ea-8069-e97b2885ca74.png)

You can try some of the glossary popups in PEP-Easy on Psybrarian using the testAccount001 login (or whatever test login I gave you).  Just pick a non-embargoed pub, and then click on one of the underlined words to see the glossary popup.  Here's an example nonembargoed doc link http://pepeasy.psybrarian.com/#/Document/PAQ.073.0005A

Small group term examples from that page:
- Relation
- Subject
- Perception
- Recognition

Large group terms:
- intersubjectivity
- object
- object relations

Small group example pic:

![image](https://user-images.githubusercontent.com/4837554/93019886-d29bf080-f5a7-11ea-844e-43eeefe6401b.png)

**Comment by bakerac4** [comment]
@nrshapiro Im taking a look at https://stage-api.pep-web.rocks/docs#/Documents/documents_glossary_term_v2_Documents_Glossary__term_id___get

but I don't see those updates? I believe that should be the correct location right?

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 

Not sure what happened, should have been there, shows update 1 day ago.  I just pushed another update there...it also ran just fine on the pipelines, but isn't showing up.  Version should show 9-13.

I'm just doing the push to Stage and it said it worked.  As did yesterdays.  But the stage-api server still shows the 9-08 server.

![image](https://user-images.githubusercontent.com/4837554/93122777-1c163980-f695-11ea-91c9-d6f93abf0c7c.png)

**Comment by lhorne-gavant** [comment]
Hi @nrshapiro,
I took a look at the beanstalk deployment and it looks like some configuration was added (FILESYSTEM_ROOT). Would you mind sharing any new fields and their expected values and i'll get them added to the deployment.
Thanks!

**Comment by nrshapiro** [comment]
That's just for the load program I'm now testing to load for you...but I 
just put the latest localsecrets in the dropbox folder for you.

Regards--Neil

------ Original Message ------

**Comment by nrshapiro** [comment]
@lhorne-gavant 

In fact, it's used in the new AWS opasDataLoader (the new name for awsS3Loader, since i want to consolidate it with local PC loader).  Not used anywhere in the server, so I'm surprised if that's why (also the process showed success to me (without looking at the logs).

(And I just added it yesterday, or the day before, while the loader file system (for S3), but it's only for the XML files, and redundant with XML_ORIGINALS_PATH, which other than not saying root, is clearer.  

FYI I'm going to consolidate the two in favor of XML_ORIGINALS_PATH in opasDataLoader, before I push it to Git for you.  This new version has fewer switches/options which should make it easier for you to understand what you need to set.  Basically, it either loads everything, only what's changed from solr,  and optionally you can also filter on the file date, so that update goes faster.  (Going through the 140K files to check can take some time.)

But as before, this limited change in localsecrets has nothing to do with the server program itself.  it's just the load program that I'm currently working on.

**Comment by nrshapiro** [comment]
@bakerac4 

Oh Sh*t...I left those extra parameters in from a early revision.  I didn't want to do it that way int the end because it would create an incompatibility.  

That's not how it works, if you look at the online documentation.  I modified it but wanted to leave it compatible.

There is now a query parameter called termidtype which determines the type of {term_id}  

https://stage-api.pep-web.rocks/v2/Documents/Glossary/ANXIETY/?termidtype=Group

See the interactive docs to try it, but watch out for the query parameters I left in by accident.

Note also that term_id seems to be case sensitive.  I'll have to look at why I didn't deal with that when I get rid of the extra parameters.

**Comment by nrshapiro** [comment]
Changes in working code: 
- Removed extra parameters
- Changed name of path parameter to be a little more generic
- Fixed path parameter description to broaden beyond ID
- Changed query to at least partly work around case sensitivity issue (even though the field itself is case sensitive)
   - if the data in the field is all uppercase, or lowercase you can enter anycase
   - if the data in the field is mixed case, you need to use the exact same case. 
       - I don't know a workaround for this...strings are case sensitive in Solr, and the only workaround for it is to use a text field, which matches differently given multiple words in search terms.  Someday I'll find a good workaround!

Next push.  Sorry about that.

**Comment by nrshapiro** [comment]
@bakerac4 

I loaded this on Stage last night.  There's one issue I noted if you try to search Terms that have (dates) in parentheses after the word...they don't seem to work...I'm looking into that.  Groups don't have that, as far as I've seen, and the word cloud should be from groups.

**Comment by bakerac4** [comment]
@nrshapiro Im trying to load a term found in a document

```
<impx type="TERM2" rx="ZBK.069.0001c.YN0011849881830" grpname="Complex">complex</impx>
```
using the endpoint like
```
https://stage-api.pep-web.rocks/v2/Documents/Glossary/ZBK.069.0001c.YN0011849881830/?termidtype=ID
```
Is that the correct way to load it? Im currently getting 0 items back but I would have assumed it would work.

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio @lhorne-gavant 
This is how you would do it...but unfortunately, the latest Solr schema update was ready and when I pushed it to stage, it doesn't work.  The IP changed, and perhaps the localsecrets file (@lhorne-gavant ) isn't updated correctly for the new IP?

Nothing is working now.

https://stage-api.pep-web.rocks/v2/Documents/Glossary/YN0011849881830/?termidtype=ID

**Comment by lhorne-gavant** [comment]
@nrshapiro I see that you just deployed to staging. It can take a couple of minutes for Solr to come up. Staging looks like it's up and the url you pasted is returning 200. Was there something in particular that looks broken?

**Comment by nrshapiro** [comment]
@lhorne-gavant @bakerac4 @adistasio 

Ok, it is up again.  It showed as done (and up on stage) in gitLab.  So I tried it from the Docs interface and nothing was working.  But it is now.  (Sigh of relief!)
