### ISSUE TITLE
Reports API

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#71]
@nrshapiro 
I am still failing to get the reports to work.  I am sure it must be something I am not doing properly.  Should this work?
https://stage-api.pep-web.rocks/v2/Reports/Document-Views?limit=10&x-api-authorize=pre%3Ap1E2pA3p4I2021

Please check the api key as you sent it in the zoom chat which has now gone.

Thanks

**Comment by nrshapiro** [comment]
@jwoosnam 

The key is best transmitted in the header, not the params, since it needs to be secure, but it works either way.  

But after our meeting, I was double checking to see what report you really wanted.  We had concluded long ago you didn't need the Document-Views report, since it was communicated to PaDS anyway through Permits.  So I made it into something else, useful, a statistical report rather than a log.  What you wanted was the Session-Log report, which shows all the logged endpoints which you can then use for counter reports (Note that the endpoints logged are now somewhat fewer since I can't log entries without a proper session-id and not all calls include them....but that's another story.)

After our call I decided though I should include a Document-Views report anyway, so I added it, and renamed the two to keep the statistical report.  

They are now:

- Document-View-Log
- Document-View-Stat

which you can see in the online Docs page (and you can test it there too).

However, the version I had online was sort of "between" versions in that way...I was holding back the new models.py definitions, which included the enum for report names, because I was considering adding another field in the DocumentListItems for more detailed author information.  I had built that locally, but didn't want to put it online since it required a complete database update, which takes a day.  Unfortunately, holding models.py back with the new names was creating a problem for the "in-between" versions, which is what you encountered.

I went ahead and put it in the latest server though--you can test here:

https://stage-api.pep-web.rocks/v2/Reports/Document-View-Log?limit=100&x-api-authorize=pre%3Ap1E2pA3p4I2021

BUT: you shouldn't be posting keys here...this is a public issues database, and the private key is secret.  I'm going to change it next push as a result.  I'll email you the new one.

Watch your email for the new key, which will be in 2020.1022.2.Alpha.  Meanwhile, 2020.1022.1 version will work with the old key as posted above.

**Comment by jwoosnam** [comment]
@nrshapiro 
Thanks Neil, the reports are now working against the new key (Sorry about showing the old one on here).  As you said the Document-View_log doesn't give me much more than I have in PaDS, but searches is useful.  I am hoping I won't need the session log as it is going to be difficult to interpret what each one means.
Couple of observations:
1) Would it be possible to have the seconds on the times?  Counter report says that the same request for the same session/user within 30 seconds is one event.
2) I am still getting 2 permit checks very close to each other in time.
3) I was running document requests from your api to check an alternative way of producing log entries and found the following gave me the full text.  If I added a valid, or invalid sessionId, it worked as expected.
https://stage-api.pep-web.rocks/v2/Documents/Document/PAQ.087.0392A/?return_format=HTML 

Have a good weekend.

**Comment by nrshapiro** [comment]
@jwoosnam @adistasio 

1.  The seconds are already included in the time:  last_update is 23 of October hr:3pm min:25 min and sec:41
```
        "row": {
          "user_id": 500004,
          "session_id": "95169298-456A-4837-9145-D5FC7F961BD6",
          "session_start": "2020-10-23T15:20:15",
          "item_of_interest": null,
          "endpoint": "/Database/Search/",
          "params": "http://stage-api.pep-web.rocks/v2/Database/Search/?abstract=true&formatrequested=XML&fulltext1=art_id%3A(CJP.024A.0233A+OR+IJP.027.0099A)&synonyms=false",
          "return_status_code": 200,
          "return_added_status_message": "1 hits; similar documents per result requested:0; queryAnalysis: False",
          "last_update": "2020-10-23T15:25:41"
        }
```

2.  The client currently requests the same document twice in a row, as the logs show.

```

  | 2020-10-23T11:55:23.158-04:00 | 2020-10-23 15:55:23 main documents_document_fetch 4266 - INFO 2:95169298-456A-4837-9145-D5FC7F961BD6: Document fetch (access: True; doc length: 148904
-- | -- | --
  | 2020-10-23T11:55:28.435-04:00 | 2020-10-23 15:55:23 main log_endpoint_time 324 - INFO ***/v2/Documents/Document/IJP.027.0099A/ response time: 2.115877866744995***
  | 2020-10-23T11:56:38.962-04:00 | 2020-10-23 15:56:38 main log_endpoint 318 - INFO ***[2:80B8C52A-CAF9-4A5A-87D1-90DE201BC0D3]:/v2/Documents/Document/ZBK.026.0333A/***
  | 2020-10-23T11:56:39.212-04:00 | 2020-10-23 15:56:38 main log_endpoint 320 - INFO ....{'documentID': 'ZBK.026.0333A'}
  | 2020-10-23T11:56:39.462-04:00 | 2020-10-23 15:56:39 main documents_document_fetch 4266 - INFO 2:80B8C52A-CAF9-4A5A-87D1-90DE201BC0D3: Document fetch (access: True; doc length: 1928
  | 2020-10-23T11:56:39.712-04:00 | 2020-10-23 15:56:39 main log_endpoint_time 324 - INFO ***/v2/Documents/Document/ZBK.026.0333A/ response time: 0.37830662727355957***
  | 2020-10-23T11:56:39.712-04:00 | 2020-10-23 15:56:39 main log_endpoint 318 - INFO ***[2:80B8C52A-CAF9-4A5A-87D1-90DE201BC0D3]:/v2/Database/Search/***
  | 2020-10-23T11:56:39.712-04:00 | 2020-10-23 15:56:39 main log_endpoint_time 324 - INFO ***/v2/Database/Search/ response time: 0.05624675750732422***
  | 2020-10-23T11:56:39.712-04:00 | 2020-10-23 15:56:39 main log_endpoint 318 - INFO ***[2:80B8C52A-CAF9-4A5A-87D1-90DE201BC0D3]:/v2/Documents/Document/ZBK.026.0333A/***
  | 2020-10-23T11:56:39.712-04:00 | 2020-10-23 15:56:39 main log_endpoint 320 - INFO ....{'documentID': 'ZBK.026.0333A'}
  | 2020-10-23T11:56:39.712-04:00 | 2020-10-23 15:56:39 main log_endpoint 318 - INFO ***[666:None]:/v2/Documents/Image/bannerZBKLogo.gif/***
  | 2020-10-23T11:56:39.962-04:00 | 2020-10-23 15:56:39 main log_endpoint 320 - INFO ....{'imageID': 'bannerZBKLogo.gif'}
  | 2020-10-23T11:56:39.962-04:00 | 2020-10-23 15:56:39 main documents_document_fetch 4266 - INFO 2:80B8C52A-CAF9-4A5A-87D1-90DE201BC0D3: Document fetch (access: True; doc length: 1928
  | 2020-10-23T11:56:45.435-04:00 | 2020-10-23 15:56:39 main log_endpoint_time 324 - INFO ***/v2/Documents/Document/ZBK.026.0333A/ response time: 0.26854467391967773***
```

**Comment by jwoosnam** [comment]
@nrshapiro 
1) Oh.....Excel had decided to hide the seconds - sorry
<img width="207" alt="Screenshot 2020-10-23 at 17 37 12" src="https://user-images.githubusercontent.com/70103034/97030460-b603b880-1556-11eb-91d0-0dbc7f5236c1.png">

2) I thought it might be that - thanks
