### ISSUE TITLE
Update Get Configuration Endpoint to Accept Multiple Configs

### ISSUE THREAD

**Issue by adistasio** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#89]
Can we please update /v2/Client/Configuration/?configname="pepweb2021" to accept and return multiple configs. So instead the url would be /v2/Client/Configuration/?confignames="pepweb2021,pepweb2020" and it would return an array of configs.

**Comment by nrshapiro** [comment]
@adistasio  Can you give me a concrete example of the settings you would be storing in each separately named config?  I'm trying to understand the need for doing this at the top level versus within the settings dict itself.

**Comment by nrshapiro** [comment]
What I'm wondering is, since I presume this request is in order to handle settings in multiple languages, why you wouldn't you just nest the languages within the configSettings as needed?  

This way they are all together and only a single save, update, delete is needed.  And this method requires no server changes.

Body of call for an add:
{
	"configName": "SpecificSettings",
	"configSettings": {
		"Setting1": {
			"en": {
				"a": "123",
				"b": "345"
			},
			"fr": {
				"a": "123",
				"b": "345"
			}
		},
		"Setting2nonLangSpecific": "123abc",
		"Setting3": {
			"en": {
				"a": "123",
				"b": "345"
			},
			"fr": {
				"a": "123",
				"b": "345"
			}
		}
	}
}

Then you only have to do the call once, and it can also be stored under a single setting name.
